server.port: 8183
# DATABASE
#   - TABLE
#     - RECORDS
#       - RECORDS
#   - TABLE
#  jpa:
#    hibernate:
#      ddl-auo: update
#  datasource:
#    url: jdbc:mysql://localhost/test_project_db
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      minIdle: 10
#      idle-timeout: 10000
#      maximumPoolSize: 30
# this should go in the LOCAL profile
# Should access at: http://localhost:8183/h2
spring:
  application:
    name: user-crud
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8661/eureka
  instance:
    hostname: localhost
